api = "0.2"

[buildpack]
  id = "com.mikusa.rust"
  name = "Rust Build Pack"
  version = "0.0.1"
  homepage = "https://github.com/dmikusa/rust-cnb"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "com.mikusa.rust-dist"
    sha256 = "98bb6327a75c6f8310b6d5b73cdfdee370cb8e8486c12481a794c2876708e67c"
    source = "https://github.com/dmikusa/rust-dist-cnb/archive/v0.0.1.tar.gz"
    source_sha256 = "8c8d43e63685a414c73785b40d4ae7d89089ba21adfd47abd395d63bf8ca543a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/dmikusa/rust-dist-cnb/releases/download/v0.0.1/rust-dist-v0.0.1.tgz"
    version = "0.0.1"

  [[metadata.dependencies]]
    id = "com.mikusa.rust-cargo"
    sha256 = "726905e23c156ff450117ea13cd421dcdb6db226a46665034ae1da7d24b4d87e"
    source = "https://github.com/dmikusa/rust-cargo-cnb/archive/v0.0.1.tar.gz"
    source_sha256 = "a4d1c19e6c3b89eccccd0397c5d74cf80a7850246a8d71b6fba0454c47f22c50"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/dmikusa/rust-cargo-cnb/releases/download/v0.0.1/rust-cargo-v0.0.1.tgz"
    version = "0.0.1"

[[order]]

  [[order.group]]
    id = "com.mikusa.rust-dist"
    version="0.0.1"

  [[order.group]]
    id = "com.mikusa.rust-cargo"
    version="0.0.1"