description = "A sample Builder for using Rust related CNBs"

[[buildpacks]]
  id = "com.mikusa.rust-dist"
  image = "dmikusa/rust-dist:v0.0.4"

[[buildpacks]]
  id = "com.mikusa.rust-cargo"
  image = "dmikusa/rust-cargo:v0.0.2"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  image = "gcr.io/paketo-buildpacks/procfile:2.0.2"

[[order]]

group = [
    { id = "com.mikusa.rust-dist", version="0.0.4"},
    { id = "com.mikusa.rust-cargo", version="0.0.2"},
    { id = "paketo-buildpacks/procfile", version="2.0.2", optional=true},
]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "gcr.io/paketo-buildpacks/build:base-cnb"
  run-image = "gcr.io/paketo-buildpacks/run:base-cnb"

# Swap the stack if you want more packages
# [stack]
#   id = "io.buildpacks.stacks.bionic"
#   build-image = "gcr.io/paketo-buildpacks/build:full-cnb-cf"
#   run-image = "gcr.io/paketo-buildpacks/run:full-cnb-cf"

# Swap the stack if you want less packages
# [stack]
#   id = "io.buildpacks.stacks.bionic"
#   build-image = "gcr.io/paketo-buildpacks/build:tiny-cnb"
#   run-image = "gcr.io/paketo-buildpacks/run:tiny-cnb"