api = "0.2"

[buildpack]
  id = "com.mikusa.rust"
  name = "Rust Build Pack"
  version = "0.0.5"
  homepage = "https://github.com/dmikusa/rust-cnb"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "com.mikusa.rust-dist"
    image = "dmikusa/rust-dist:v0.0.3"

  [[metadata.dependencies]]
    id = "com.mikusa.rust-cargo"
    image = "dmikusa/rust-cargo:v0.0.2"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/procfile"
    image = "gcr.io/paketo-buildpacks/procfile:1.3.8"

[[order]]

  [[order.group]]
    id = "com.mikusa.rust-dist"
    version="0.0.3"

  [[order.group]]
    id = "com.mikusa.rust-cargo"
    version="0.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version="1.3.8"
    optional = true