description = "A sample Builder for using Rust related CNBs"

[[buildpacks]]
  id = "com.mikusa.rust-dist"
  uri = "docker://dmikusa/rust-dist:v0.0.7"

[[buildpacks]]
  id = "com.mikusa.rust-cargo"
  uri = "docker://dmikusa/rust-cargo:v0.0.3"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:3.0.0"

[[order]]

group = [
    { id = "com.mikusa.rust-dist", version="0.0.7"},
    { id = "com.mikusa.rust-cargo", version="0.0.3"},
    { id = "paketo-buildpacks/procfile", version="3.0.0", optional=true},
]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "gcr.io/paketo-buildpacks/build:base-cnb"
  run-image = "gcr.io/paketo-buildpacks/run:base-cnb"

# Swap the stack if you want more packages
# [stack]
#   id = "io.buildpacks.stacks.bionic"
#   build-image = "gcr.io/paketo-buildpacks/build:full-cnb-cf"
#   run-image = "gcr.io/paketo-buildpacks/run:full-cnb-cf"

# Swap the stack if you want less packages
# [stack]
#   id = "io.paketo.stacks.tiny"
#   build-image = "gcr.io/paketo-buildpacks/build:tiny-cnb"
#   run-image = "gcr.io/paketo-buildpacks/run:tiny-cnb"