description = "A sample Builder for using Rust related CNBs"

[[buildpacks]]
  id = "paketo-community/rustup"
  uri = "docker://docker.io/paketocommunity/rustup:1.1.2"

[[buildpacks]]
  id = "paketo-community/rust-dist"
  uri = "docker://docker.io/paketocommunity/rust-dist:1.3.1"

[[buildpacks]]
  id = "paketo-community/cargo"
  uri = "docker://docker.io/paketocommunity/cargo:0.2.1"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.0.2"

[[order]]

  [[order.group]]
    id = "paketo-community/rustup"

  [[order.group]]
    id = "paketo-community/rust-dist"

  [[order.group]]
    id = "paketo-community/cargo"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[stack]
  build-image = "gcr.io/paketo-buildpacks/build:base-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "gcr.io/paketo-buildpacks/run:base-cnb"
